/**
 * Шаблоны умений (§6.5, §17). 25 умений игрока (включая strike, покрывают все
 * 11 CardKind) + 16 умений монстров/боссов (6 monster + 10 boss).
 */

import type { CardTemplate } from '../types/cards'
import { STRIKE_TEMPLATE_ID } from '../types/cards'

export const PLAYER_CARDS: CardTemplate[] = [
  // --- melee (3, включая strike) ---
  {
    id: STRIKE_TEMPLATE_ID,
    label: 'Удар',
    kind: 'melee',
    maxRange: 1,
    statSource: 'attack',
    skillFlat: 8,
    scaleToken: '0%%',
    cooldownTurns: 0,
    tags: ['melee', 'attack', 'physical'],
  },
  {
    id: 'cleave',
    label: 'Рассекающий удар',
    kind: 'melee',
    maxRange: 1,
    statSource: 'attack',
    skillFlat: 14,
    scaleToken: '40%%',
    cooldownTurns: 2,
    tags: ['melee', 'attack', 'physical'],
  },
  {
    id: 'heavy_blow',
    label: 'Тяжёлый замах',
    kind: 'melee',
    maxRange: 1,
    statSource: 'attack',
    skillFlat: 22,
    scaleToken: '50%%80',
    cooldownTurns: 3,
    tags: ['melee', 'attack', 'physical'],
  },
  // --- ranged (3) ---
  {
    id: 'piercing_shot',
    label: 'Пронзающий выстрел',
    kind: 'ranged',
    maxRange: 4,
    statSource: 'attack',
    skillFlat: 12,
    scaleToken: '35%%',
    cooldownTurns: 2,
    tags: ['ranged', 'attack', 'physical'],
  },
  {
    id: 'arcane_bolt',
    label: 'Чародейская стрела',
    kind: 'ranged',
    maxRange: 5,
    statSource: 'magicPower',
    skillFlat: 14,
    scaleToken: '45%%',
    cooldownTurns: 2,
    tags: ['ranged', 'skill', 'shadow'],
  },
  {
    id: 'venom_arrow',
    label: 'Ядовитая стрела',
    kind: 'ranged',
    maxRange: 4,
    statSource: 'attack',
    skillFlat: 10,
    scaleToken: '30%%60',
    cooldownTurns: 2,
    tags: ['ranged', 'attack', 'poison'],
  },
  // --- aoe (3) ---
  {
    id: 'fireball',
    label: 'Огненный шар',
    kind: 'aoe',
    maxRange: 5,
    statSource: 'magicPower',
    skillFlat: 18,
    scaleToken: '40%%',
    cooldownTurns: 3,
    tags: ['aoe', 'skill', 'fire'],
    aoeRadius: 1,
  },
  {
    id: 'frost_nova',
    label: 'Морозная вспышка',
    kind: 'aoe',
    maxRange: 3,
    statSource: 'magicPower',
    skillFlat: 14,
    scaleToken: '30%%70',
    cooldownTurns: 3,
    tags: ['aoe', 'skill', 'ice'],
    aoeRadius: 1,
  },
  {
    id: 'meteor',
    label: 'Метеор',
    kind: 'aoe',
    maxRange: 6,
    statSource: 'magicPower',
    skillFlat: 26,
    scaleToken: '55%%90',
    cooldownTurns: 4,
    tags: ['aoe', 'skill', 'fire'],
    aoeRadius: 2,
  },
  // --- heal (2) ---
  {
    id: 'heal',
    label: 'Исцеление',
    kind: 'heal',
    maxRange: 4,
    statSource: 'healPower',
    skillFlat: 16,
    scaleToken: '40%%',
    cooldownTurns: 2,
    tags: ['heal', 'skill', 'holy'],
  },
  {
    id: 'greater_heal',
    label: 'Великое исцеление',
    kind: 'heal',
    maxRange: 4,
    statSource: 'healPower',
    skillFlat: 30,
    scaleToken: '50%%',
    cooldownTurns: 3,
    tags: ['heal', 'skill', 'holy'],
  },
  // --- regen (2) ---
  {
    id: 'regeneration',
    label: 'Регенерация',
    kind: 'regen',
    maxRange: 4,
    statSource: 'healPower',
    skillFlat: 6,
    scaleToken: '25%%',
    cooldownTurns: 3,
    tags: ['heal', 'skill', 'holy'],
    status: {
      id: 'regeneration',
      duration: 3,
      tickAmount: 8,
      tickToken: '25%%',
    },
  },
  {
    id: 'sanctuary',
    label: 'Святилище',
    kind: 'regen',
    maxRange: 3,
    statSource: 'healPower',
    skillFlat: 5,
    scaleToken: '20%%50',
    cooldownTurns: 4,
    tags: ['heal', 'skill', 'holy'],
    status: {
      id: 'sanctuary',
      duration: 4,
      statMods: { defense: 4 },
      tickAmount: 6,
      tickToken: '20%%50',
    },
  },
  // --- resurrect (1) ---
  {
    id: 'resurrection',
    label: 'Воскрешение',
    kind: 'resurrect',
    maxRange: 3,
    statSource: 'healPower',
    skillFlat: 20,
    scaleToken: '40%%',
    cooldownTurns: 4,
    tags: ['heal', 'skill', 'holy'],
  },
  // --- buff (3) ---
  {
    id: 'battle_cry',
    label: 'Боевой клич',
    kind: 'buff',
    maxRange: 3,
    statSource: 'attack',
    skillFlat: 0,
    scaleToken: '15%%50',
    cooldownTurns: 3,
    tags: ['skill', 'attack', 'physical'],
    status: {
      id: 'battle_cry',
      duration: 3,
      statMods: { attack: 10, critChance: 5 },
    },
  },
  {
    id: 'blessing',
    label: 'Благословение',
    kind: 'buff',
    maxRange: 4,
    statSource: 'healPower',
    skillFlat: 0,
    scaleToken: '12%%',
    cooldownTurns: 3,
    tags: ['skill', 'heal', 'holy'],
    status: {
      id: 'blessing',
      duration: 3,
      statMods: { defense: 8, healPower: 6 },
    },
  },
  {
    id: 'haste',
    label: 'Ускорение',
    kind: 'buff',
    maxRange: 3,
    statSource: 'speed',
    skillFlat: 0,
    scaleToken: '10%%40',
    cooldownTurns: 2,
    tags: ['skill', 'attack'],
    status: {
      id: 'haste',
      duration: 2,
      statMods: { speed: 2, initiative: 12 },
    },
  },
  // --- debuff (3) ---
  {
    id: 'weaken',
    label: 'Ослабление',
    kind: 'debuff',
    maxRange: 4,
    statSource: 'magicPower',
    skillFlat: 0,
    scaleToken: '12%%-30',
    cooldownTurns: 2,
    tags: ['skill', 'shadow'],
    status: {
      id: 'weaken',
      duration: 3,
      statMods: { attack: -10, magicPower: -8 },
    },
  },
  {
    id: 'curse',
    label: 'Проклятие',
    kind: 'debuff',
    maxRange: 5,
    statSource: 'magicPower',
    skillFlat: 0,
    scaleToken: '15%%-40',
    cooldownTurns: 3,
    tags: ['skill', 'shadow'],
    status: {
      id: 'curse',
      duration: 3,
      statMods: { defense: -12, initiative: -10 },
    },
  },
  {
    id: 'armor_break',
    label: 'Пробитие брони',
    kind: 'debuff',
    maxRange: 1,
    statSource: 'attack',
    skillFlat: 0,
    scaleToken: '10%%-25',
    cooldownTurns: 2,
    tags: ['skill', 'attack', 'physical'],
    status: {
      id: 'armor_break',
      duration: 2,
      statMods: { defense: -15 },
    },
  },
  // --- dot (2) ---
  {
    id: 'poison_dart',
    label: 'Отравленный дротик',
    kind: 'dot',
    maxRange: 4,
    statSource: 'magicPower',
    skillFlat: 4,
    scaleToken: '20%%-40',
    cooldownTurns: 2,
    tags: ['skill', 'poison'],
    status: {
      id: 'poison_dart',
      duration: 3,
      tickAmount: -7,
      tickToken: '25%%',
      damageTag: 'poison',
    },
  },
  {
    id: 'immolation',
    label: 'Воспламенение',
    kind: 'dot',
    maxRange: 5,
    statSource: 'magicPower',
    skillFlat: 6,
    scaleToken: '30%%60',
    cooldownTurns: 3,
    tags: ['skill', 'fire'],
    status: {
      id: 'immolation',
      duration: 3,
      tickAmount: -10,
      tickToken: '30%%',
      damageTag: 'fire',
    },
  },
  // --- lifesteal_spell (2) ---
  {
    id: 'drain_life',
    label: 'Высасывание жизни',
    kind: 'lifesteal_spell',
    maxRange: 4,
    statSource: 'magicPower',
    skillFlat: 14,
    scaleToken: '40%%',
    cooldownTurns: 3,
    tags: ['skill', 'shadow'],
  },
  {
    id: 'soul_siphon',
    label: 'Похищение души',
    kind: 'lifesteal_spell',
    maxRange: 5,
    statSource: 'magicPower',
    skillFlat: 20,
    scaleToken: '45%%80',
    cooldownTurns: 4,
    tags: ['skill', 'shadow'],
  },
  // --- utility (1) ---
  {
    id: 'smoke_bomb',
    label: 'Дымовая бомба',
    kind: 'utility',
    maxRange: 3,
    statSource: 'speed',
    skillFlat: 0,
    scaleToken: '10%%40',
    cooldownTurns: 3,
    tags: ['skill', 'utility'],
  },
]

export const MONSTER_CARDS: CardTemplate[] = [
  {
    id: 'monster_bite',
    label: 'Укус',
    kind: 'melee',
    maxRange: 1,
    statSource: 'attack',
    skillFlat: 12,
    scaleToken: '35%%',
    cooldownTurns: 1,
    tags: ['melee', 'attack', 'physical'],
  },
  {
    id: 'monster_claw',
    label: 'Рассечение когтями',
    kind: 'melee',
    maxRange: 1,
    statSource: 'attack',
    skillFlat: 16,
    scaleToken: '40%%70',
    cooldownTurns: 2,
    tags: ['melee', 'attack', 'physical'],
  },
  {
    id: 'monster_spit',
    label: 'Кислотный плевок',
    kind: 'ranged',
    maxRange: 4,
    statSource: 'magicPower',
    skillFlat: 10,
    scaleToken: '30%%',
    cooldownTurns: 2,
    tags: ['ranged', 'skill', 'poison'],
  },
  {
    id: 'monster_venom',
    label: 'Ядовитые миазмы',
    kind: 'dot',
    maxRange: 3,
    statSource: 'magicPower',
    skillFlat: 4,
    scaleToken: '20%%-40',
    cooldownTurns: 3,
    tags: ['skill', 'poison'],
    status: {
      id: 'monster_venom',
      duration: 3,
      tickAmount: -6,
      tickToken: '25%%',
      damageTag: 'poison',
    },
  },
  {
    id: 'monster_roar',
    label: 'Устрашающий рёв',
    kind: 'debuff',
    maxRange: 3,
    statSource: 'attack',
    skillFlat: 0,
    scaleToken: '10%%-25',
    cooldownTurns: 3,
    tags: ['skill', 'shadow'],
    status: {
      id: 'monster_roar',
      duration: 2,
      statMods: { attack: -8, defense: -6 },
    },
  },
  {
    id: 'monster_pack_howl',
    label: 'Вой стаи',
    kind: 'buff',
    maxRange: 4,
    statSource: 'attack',
    skillFlat: 0,
    scaleToken: '12%%50',
    cooldownTurns: 3,
    tags: ['skill', 'attack'],
    status: {
      id: 'monster_pack_howl',
      duration: 3,
      statMods: { attack: 8, speed: 1 },
    },
  },
]

export const BOSS_CARDS: CardTemplate[] = [
  {
    id: 'boss_earthshatter',
    label: 'Сотрясение земли',
    kind: 'aoe',
    maxRange: 6,
    statSource: 'attack',
    skillFlat: 40,
    scaleToken: '60%%90',
    cooldownTurns: 3,
    tags: ['aoe', 'attack', 'physical'],
    aoeRadius: 2,
    enabled: true,
  },
  {
    id: 'boss_inferno',
    label: 'Адское пламя',
    kind: 'aoe',
    maxRange: 6,
    statSource: 'magicPower',
    skillFlat: 44,
    scaleToken: '65%%',
    cooldownTurns: 4,
    tags: ['aoe', 'skill', 'fire'],
    aoeRadius: 2,
    enabled: true,
  },
  {
    id: 'boss_death_grip',
    label: 'Хватка смерти',
    kind: 'melee',
    maxRange: 1,
    statSource: 'attack',
    skillFlat: 50,
    scaleToken: '70%%',
    cooldownTurns: 2,
    tags: ['melee', 'attack', 'shadow'],
    enabled: true,
  },
  {
    id: 'boss_soul_drain',
    label: 'Поглощение душ',
    kind: 'lifesteal_spell',
    maxRange: 5,
    statSource: 'magicPower',
    skillFlat: 38,
    scaleToken: '60%%85',
    cooldownTurns: 3,
    tags: ['skill', 'shadow'],
    enabled: true,
  },
  {
    id: 'boss_unholy_nova',
    label: 'Нечестивая вспышка',
    kind: 'aoe',
    maxRange: 4,
    statSource: 'magicPower',
    skillFlat: 36,
    scaleToken: '55%%80',
    cooldownTurns: 3,
    tags: ['aoe', 'skill', 'shadow'],
    aoeRadius: 2,
    enabled: true,
  },
  {
    id: 'boss_dark_blessing',
    label: 'Тёмное благословение',
    kind: 'buff',
    maxRange: 4,
    statSource: 'magicPower',
    skillFlat: 0,
    scaleToken: '20%%60',
    cooldownTurns: 3,
    tags: ['skill', 'shadow'],
    status: {
      id: 'boss_dark_blessing',
      duration: 3,
      statMods: { attack: 20, defense: 15, critChance: 10 },
    },
    enabled: true,
  },
  {
    id: 'boss_terror',
    label: 'Ужас',
    kind: 'debuff',
    maxRange: 5,
    statSource: 'magicPower',
    skillFlat: 0,
    scaleToken: '20%%-50',
    cooldownTurns: 3,
    tags: ['skill', 'shadow'],
    status: {
      id: 'boss_terror',
      duration: 3,
      statMods: { attack: -20, defense: -18, initiative: -20 },
    },
    enabled: true,
  },
  {
    id: 'boss_meteor_storm',
    label: 'Метеоритный шторм',
    kind: 'aoe',
    maxRange: 7,
    statSource: 'magicPower',
    skillFlat: 52,
    scaleToken: '70%%90',
    cooldownTurns: 4,
    tags: ['aoe', 'skill', 'fire'],
    aoeRadius: 3,
    enabled: true,
  },
  {
    id: 'boss_life_reap',
    label: 'Жатва жизни',
    kind: 'lifesteal_spell',
    maxRange: 1,
    statSource: 'attack',
    skillFlat: 46,
    scaleToken: '65%%',
    cooldownTurns: 2,
    tags: ['melee', 'attack', 'shadow'],
    enabled: true,
  },
  {
    id: 'boss_doom_bolt',
    label: 'Стрела погибели',
    kind: 'ranged',
    maxRange: 7,
    statSource: 'magicPower',
    skillFlat: 48,
    scaleToken: '65%%',
    cooldownTurns: 2,
    tags: ['ranged', 'skill', 'shadow'],
    enabled: true,
  },
]

export const ALL_CARDS: CardTemplate[] = [...PLAYER_CARDS, ...MONSTER_CARDS, ...BOSS_CARDS]
