/**
 * Архетипы врагов (§13, §17). 31 архетип = 16 counter + 3 chaotic +
 * 4 hero NPC + 8 boss. Боссы — по 1 на класс героя.
 */

import type { StatBlock } from '../types/stats'
import { zeroStats } from '../types/stats'
import type { EnemyArchetype, SkillPreset } from '../types/content'

/** Собрать полный StatBlock из частичного описания. */
function S(p: Partial<StatBlock>): StatBlock {
  return { ...zeroStats(), ...p }
}

/** Пресет умения без модов. */
function skill(templateId: string, level: number): SkillPreset {
  return { templateId, level, modSlots: [] }
}

// ---------------------------------------------------------------------------
// 16 counter-архетипов (по 2 на каждый из 8 классов героев)
// ---------------------------------------------------------------------------

interface CounterSpec {
  id: string
  label: string
  raceId: string
  counterClass: string
  baseAttack: EnemyArchetype['baseAttack']
  stats: Partial<StatBlock>
  skills: [string, number][]
  passives: [string, number][]
  priorities: string[]
  threatTags: string[]
  spawnWeight: number
  emoji: string
}

const COUNTERS: CounterSpec[] = [
  {
    id: 'counter_warrior_shieldbreaker',
    label: 'Сокрушитель щитов',
    raceId: 'orc',
    counterClass: 'warrior',
    baseAttack: 'strike',
    stats: { health: 120, attack: 28, defense: 14, speed: 3, initiative: 40 },
    skills: [['monster_claw', 4]],
    passives: [['epass_savage', 3]],
    priorities: ['monster_claw'],
    threatTags: ['bruiser', 'anti_armor'],
    spawnWeight: 10,
    emoji: '👹',
  },
  {
    id: 'counter_warrior_duelist',
    label: 'Орочий дуэлянт',
    raceId: 'orc',
    counterClass: 'warrior',
    baseAttack: 'strike',
    stats: { health: 100, attack: 24, defense: 10, speed: 4, initiative: 55 },
    skills: [['monster_bite', 3], ['monster_roar', 2]],
    passives: [['epass_frenzied', 2]],
    priorities: ['monster_roar', 'monster_bite'],
    threatTags: ['bruiser'],
    spawnWeight: 12,
    emoji: '👹',
  },
  {
    id: 'counter_mage_silencer',
    label: 'Гончая чар',
    raceId: 'beast',
    counterClass: 'mage',
    baseAttack: 'strike',
    stats: { health: 80, attack: 22, defense: 6, speed: 6, initiative: 70 },
    skills: [['monster_bite', 4]],
    passives: [['epass_savage', 3]],
    priorities: ['monster_bite'],
    threatTags: ['assassin', 'anti_caster'],
    spawnWeight: 11,
    emoji: '🐺',
  },
  {
    id: 'counter_mage_nullifier',
    label: 'Пожиратель магии',
    raceId: 'demon',
    counterClass: 'mage',
    baseAttack: 'magic_bolt',
    stats: { health: 95, magicPower: 26, defense: 8, speed: 4, initiative: 50 },
    skills: [['monster_spit', 3], ['monster_roar', 3]],
    passives: [['epass_ward', 2]],
    priorities: ['monster_spit', 'monster_roar'],
    threatTags: ['caster', 'anti_caster'],
    spawnWeight: 9,
    emoji: '👺',
  },
  {
    id: 'counter_ranger_charger',
    label: 'Бронированный таран',
    raceId: 'construct',
    counterClass: 'ranger',
    baseAttack: 'strike',
    stats: { health: 130, attack: 24, defense: 18, speed: 5, initiative: 45 },
    skills: [['monster_claw', 3]],
    passives: [['epass_thick_hide', 3]],
    priorities: ['monster_claw'],
    threatTags: ['tank', 'gap_closer'],
    spawnWeight: 8,
    emoji: '🤖',
  },
  {
    id: 'counter_ranger_skirmisher',
    label: 'Загонщик стаи',
    raceId: 'beast',
    counterClass: 'ranger',
    baseAttack: 'shot',
    stats: { health: 85, attack: 22, defense: 6, speed: 6, initiative: 65 },
    skills: [['monster_spit', 3], ['monster_pack_howl', 2]],
    passives: [['epass_frenzied', 2]],
    priorities: ['monster_pack_howl', 'monster_spit'],
    threatTags: ['skirmisher'],
    spawnWeight: 11,
    emoji: '🐺',
  },
  {
    id: 'counter_healer_executioner',
    label: 'Палач исцелителей',
    raceId: 'undead',
    counterClass: 'healer',
    baseAttack: 'strike',
    stats: { health: 110, attack: 30, defense: 10, speed: 5, initiative: 60 },
    skills: [['monster_claw', 4], ['monster_roar', 2]],
    passives: [['epass_undying', 2]],
    priorities: ['monster_claw', 'monster_roar'],
    threatTags: ['assassin', 'anti_support'],
    spawnWeight: 9,
    emoji: '💀',
  },
  {
    id: 'counter_healer_plaguebearer',
    label: 'Чумоносец',
    raceId: 'undead',
    counterClass: 'healer',
    baseAttack: 'magic_bolt',
    stats: { health: 100, magicPower: 24, defense: 8, speed: 3, initiative: 48 },
    skills: [['monster_venom', 4], ['monster_spit', 2]],
    passives: [['epass_venomous', 3]],
    priorities: ['monster_venom', 'monster_spit'],
    threatTags: ['caster', 'anti_heal'],
    spawnWeight: 10,
    emoji: '💀',
  },
  {
    id: 'counter_rogue_sentinel',
    label: 'Бдительный страж',
    raceId: 'construct',
    counterClass: 'rogue',
    baseAttack: 'strike',
    stats: { health: 115, attack: 20, defense: 16, speed: 4, initiative: 75 },
    skills: [['monster_claw', 3]],
    passives: [['epass_spiky', 3]],
    priorities: ['monster_claw'],
    threatTags: ['tank', 'anti_assassin'],
    spawnWeight: 9,
    emoji: '🤖',
  },
  {
    id: 'counter_rogue_hunter',
    label: 'Охотник на теней',
    raceId: 'elf',
    counterClass: 'rogue',
    baseAttack: 'shot',
    stats: { health: 90, attack: 24, defense: 8, speed: 6, initiative: 80 },
    skills: [['monster_spit', 3], ['monster_roar', 2]],
    passives: [['epass_warcaller', 2]],
    priorities: ['monster_spit', 'monster_roar'],
    threatTags: ['skirmisher', 'anti_assassin'],
    spawnWeight: 10,
    emoji: '🧝',
  },
  {
    id: 'counter_paladin_corruptor',
    label: 'Осквернитель',
    raceId: 'demon',
    counterClass: 'paladin',
    baseAttack: 'magic_bolt',
    stats: { health: 105, magicPower: 28, defense: 10, speed: 4, initiative: 52 },
    skills: [['monster_venom', 3], ['monster_roar', 3]],
    passives: [['epass_ward', 2]],
    priorities: ['monster_venom', 'monster_roar'],
    threatTags: ['caster', 'anti_tank'],
    spawnWeight: 8,
    emoji: '👺',
  },
  {
    id: 'counter_paladin_breaker',
    label: 'Громила-кувалда',
    raceId: 'orc',
    counterClass: 'paladin',
    baseAttack: 'strike',
    stats: { health: 140, attack: 32, defense: 12, speed: 4, initiative: 42 },
    skills: [['monster_claw', 4]],
    passives: [['epass_savage', 3]],
    priorities: ['monster_claw'],
    threatTags: ['bruiser', 'anti_tank'],
    spawnWeight: 9,
    emoji: '👹',
  },
  {
    id: 'counter_warlock_zealot',
    label: 'Светлый ревнитель',
    raceId: 'human',
    counterClass: 'warlock',
    baseAttack: 'strike',
    stats: { health: 100, attack: 26, defense: 12, speed: 5, initiative: 62 },
    skills: [['monster_bite', 3], ['monster_pack_howl', 2]],
    passives: [['epass_warcaller', 2]],
    priorities: ['monster_pack_howl', 'monster_bite'],
    threatTags: ['bruiser', 'anti_caster'],
    spawnWeight: 10,
    emoji: '🧑',
  },
  {
    id: 'counter_warlock_inquisitor',
    label: 'Инквизитор',
    raceId: 'human',
    counterClass: 'warlock',
    baseAttack: 'magic_bolt',
    stats: { health: 95, magicPower: 24, defense: 10, speed: 4, initiative: 55 },
    skills: [['monster_spit', 3], ['monster_roar', 3]],
    passives: [['epass_ward', 2]],
    priorities: ['monster_roar', 'monster_spit'],
    threatTags: ['caster', 'anti_caster'],
    spawnWeight: 9,
    emoji: '🧑',
  },
  {
    id: 'counter_berserker_chiller',
    label: 'Ледяной усмиритель',
    raceId: 'specter',
    counterClass: 'berserker',
    baseAttack: 'magic_bolt',
    stats: { health: 90, magicPower: 26, defense: 8, speed: 5, initiative: 58 },
    skills: [['monster_roar', 4], ['monster_spit', 2]],
    passives: [['epass_ward', 2]],
    priorities: ['monster_roar', 'monster_spit'],
    threatTags: ['caster', 'control'],
    spawnWeight: 9,
    emoji: '👻',
  },
  {
    id: 'counter_berserker_warden',
    label: 'Несокрушимый страж',
    raceId: 'construct',
    counterClass: 'berserker',
    baseAttack: 'strike',
    stats: { health: 150, attack: 22, defense: 20, speed: 3, initiative: 40 },
    skills: [['monster_claw', 3]],
    passives: [['epass_thick_hide', 3], ['epass_spiky', 2]],
    priorities: ['monster_claw'],
    threatTags: ['tank', 'anti_bruiser'],
    spawnWeight: 8,
    emoji: '🤖',
  },
]

const COUNTER_ARCHETYPES: EnemyArchetype[] = COUNTERS.map((c) => ({
  id: c.id,
  label: c.label,
  raceId: c.raceId,
  counterClass: c.counterClass,
  baseStats: S(c.stats),
  baseAttack: c.baseAttack,
  skillPresets: c.skills.map(([t, l]) => skill(t, l)),
  passivePresets: c.passives.map(([templateId, level]) => ({ templateId, level })),
  skillPriorities: c.priorities,
  threatTags: c.threatTags,
  spawnWeight: c.spawnWeight,
  iconEmoji: c.emoji,
}))

// ---------------------------------------------------------------------------
// 3 chaotic-архетипа (isChaotic: per-stat variance)
// ---------------------------------------------------------------------------

const CHAOTIC_ARCHETYPES: EnemyArchetype[] = [
  {
    id: 'chaotic_aberration',
    label: 'Бесформенная аберрация',
    raceId: 'demon',
    baseStats: S({ health: 110, attack: 22, magicPower: 22, defense: 10, speed: 4, initiative: 50, critChance: 10 }),
    baseAttack: 'strike',
    skillPresets: [skill('monster_claw', 3), skill('monster_venom', 3)],
    passivePresets: [{ templateId: 'epass_unstable_core', level: 3 }],
    skillPriorities: ['monster_venom', 'monster_claw'],
    threatTags: ['chaotic', 'bruiser'],
    spawnWeight: 6,
    isChaotic: true,
    iconEmoji: '🌀',
  },
  {
    id: 'chaotic_wisp_swarm',
    label: 'Рой искажающих огней',
    raceId: 'specter',
    baseStats: S({ health: 70, magicPower: 28, defense: 4, speed: 7, initiative: 75, critChance: 15 }),
    baseAttack: 'magic_bolt',
    skillPresets: [skill('monster_spit', 4)],
    passivePresets: [{ templateId: 'epass_ward', level: 2 }],
    skillPriorities: ['monster_spit'],
    threatTags: ['chaotic', 'caster'],
    spawnWeight: 7,
    isChaotic: true,
    iconEmoji: '✨',
  },
  {
    id: 'chaotic_mutant_beast',
    label: 'Мутировавший зверь',
    raceId: 'beast',
    baseStats: S({ health: 130, attack: 26, defense: 12, speed: 5, initiative: 55, critChance: 8 }),
    baseAttack: 'strike',
    skillPresets: [skill('monster_claw', 4), skill('monster_pack_howl', 2)],
    passivePresets: [{ templateId: 'epass_frenzied', level: 3 }, { templateId: 'epass_regrowth', level: 2 }],
    skillPriorities: ['monster_pack_howl', 'monster_claw'],
    threatTags: ['chaotic', 'bruiser'],
    spawnWeight: 7,
    isChaotic: true,
    iconEmoji: '🐗',
  },
]

// ---------------------------------------------------------------------------
// 4 hero NPC (с classId; враждебные «герои»)
// ---------------------------------------------------------------------------

const HERO_NPC_ARCHETYPES: EnemyArchetype[] = [
  {
    id: 'npc_renegade_warrior',
    label: 'Воин-отступник',
    raceId: 'human',
    classId: 'warrior',
    baseStats: S({ health: 150, attack: 30, defense: 16, speed: 4, initiative: 55 }),
    baseAttack: 'strike',
    skillPresets: [skill('monster_claw', 5), skill('monster_pack_howl', 3)],
    passivePresets: [{ templateId: 'epass_thick_hide', level: 4 }],
    skillPriorities: ['monster_pack_howl', 'monster_claw'],
    threatTags: ['elite', 'bruiser'],
    spawnWeight: 5,
    iconEmoji: '🧑‍✈️',
  },
  {
    id: 'npc_rogue_mercenary',
    label: 'Наёмник-разбойник',
    raceId: 'human',
    classId: 'rogue',
    baseStats: S({ health: 110, attack: 28, defense: 8, speed: 6, initiative: 90, critChance: 25 }),
    baseAttack: 'strike',
    skillPresets: [skill('monster_bite', 5)],
    passivePresets: [{ templateId: 'epass_savage', level: 4 }],
    skillPriorities: ['monster_bite'],
    threatTags: ['elite', 'assassin'],
    spawnWeight: 5,
    iconEmoji: '🥷',
  },
  {
    id: 'npc_dark_mage',
    label: 'Тёмный маг',
    raceId: 'human',
    classId: 'warlock',
    baseStats: S({ health: 100, magicPower: 34, defense: 8, speed: 4, initiative: 60, critChance: 12 }),
    baseAttack: 'magic_bolt',
    skillPresets: [skill('monster_spit', 5), skill('monster_venom', 4)],
    passivePresets: [{ templateId: 'epass_ward', level: 3 }],
    skillPriorities: ['monster_venom', 'monster_spit'],
    threatTags: ['elite', 'caster'],
    spawnWeight: 5,
    iconEmoji: '🧙‍♂️',
  },
  {
    id: 'npc_fallen_priest',
    label: 'Падший жрец',
    raceId: 'human',
    classId: 'healer',
    baseStats: S({ health: 120, magicPower: 26, healPower: 24, defense: 12, speed: 4, initiative: 50 }),
    baseAttack: 'magic_bolt',
    skillPresets: [skill('monster_roar', 4), skill('monster_spit', 3)],
    passivePresets: [{ templateId: 'epass_regrowth', level: 4 }],
    skillPriorities: ['monster_roar', 'monster_spit'],
    threatTags: ['elite', 'support'],
    spawnWeight: 5,
    iconEmoji: '🧎',
  },
]

// ---------------------------------------------------------------------------
// 8 боссов (по 1 на класс героя), isBoss + bossMechanics
// ---------------------------------------------------------------------------

export const BOSSES: EnemyArchetype[] = [
  {
    id: 'boss_warrior_ironjaw',
    label: 'Железная Челюсть, Владыка Арены',
    raceId: 'orc',
    counterClass: 'warrior',
    baseStats: S({ health: 420, attack: 48, defense: 24, speed: 4, initiative: 60 }),
    baseAttack: 'strike',
    skillPresets: [skill('boss_earthshatter', 6), skill('boss_death_grip', 6)],
    passivePresets: [{ templateId: 'epass_thick_hide', level: 6 }, { templateId: 'epass_spiky', level: 4 }],
    skillPriorities: ['boss_earthshatter', 'boss_death_grip'],
    threatTags: ['boss', 'bruiser'],
    spawnWeight: 1,
    isBoss: true,
    bossMechanics: ['reflect', 'enrage_below_half'],
    iconEmoji: '👹',
  },
  {
    id: 'boss_mage_pyrelord',
    label: 'Пиролорд Игнис',
    raceId: 'demon',
    counterClass: 'mage',
    baseStats: S({ health: 360, magicPower: 56, defense: 16, speed: 4, initiative: 65, critChance: 15 }),
    baseAttack: 'magic_bolt',
    skillPresets: [skill('boss_meteor_storm', 6), skill('boss_inferno', 6)],
    passivePresets: [{ templateId: 'epass_ward', level: 6 }],
    skillPriorities: ['boss_meteor_storm', 'boss_inferno'],
    threatTags: ['boss', 'caster'],
    spawnWeight: 1,
    isBoss: true,
    bossMechanics: ['anti_heal', 'spell_shield'],
    iconEmoji: '🔥',
  },
  {
    id: 'boss_ranger_shadowfang',
    label: 'Тенеклык, Король Охоты',
    raceId: 'beast',
    counterClass: 'ranger',
    baseStats: S({ health: 340, attack: 50, defense: 14, speed: 7, initiative: 95, critChance: 30 }),
    baseAttack: 'shot',
    skillPresets: [skill('boss_doom_bolt', 6), skill('boss_dark_blessing', 5)],
    passivePresets: [{ templateId: 'epass_frenzied', level: 6 }],
    skillPriorities: ['boss_dark_blessing', 'boss_doom_bolt'],
    threatTags: ['boss', 'skirmisher'],
    spawnWeight: 1,
    isBoss: true,
    bossMechanics: ['stealth', 'first_strike'],
    iconEmoji: '🐺',
  },
  {
    id: 'boss_healer_lifebane',
    label: 'Гниль-Жизнь, Жрица Распада',
    raceId: 'undead',
    counterClass: 'healer',
    baseStats: S({ health: 400, magicPower: 44, healPower: 30, defense: 18, speed: 3, initiative: 55 }),
    baseAttack: 'magic_bolt',
    skillPresets: [skill('boss_unholy_nova', 6), skill('boss_terror', 5)],
    passivePresets: [{ templateId: 'epass_regrowth', level: 6 }, { templateId: 'epass_undying', level: 5 }],
    skillPriorities: ['boss_terror', 'boss_unholy_nova'],
    threatTags: ['boss', 'support'],
    spawnWeight: 1,
    isBoss: true,
    bossMechanics: ['anti_heal', 'self_regen'],
    iconEmoji: '💀',
  },
  {
    id: 'boss_rogue_nightblade',
    label: 'Клинок Ночи Вэйл',
    raceId: 'elf',
    counterClass: 'rogue',
    baseStats: S({ health: 330, attack: 52, defense: 12, speed: 7, initiative: 100, critChance: 35 }),
    baseAttack: 'strike',
    skillPresets: [skill('boss_death_grip', 6), skill('boss_life_reap', 6)],
    passivePresets: [{ templateId: 'epass_savage', level: 6 }],
    skillPriorities: ['boss_life_reap', 'boss_death_grip'],
    threatTags: ['boss', 'assassin'],
    spawnWeight: 1,
    isBoss: true,
    bossMechanics: ['stealth', 'evasion'],
    iconEmoji: '🗡️',
  },
  {
    id: 'boss_paladin_doomguard',
    label: 'Страж Погибели Морн',
    raceId: 'construct',
    counterClass: 'paladin',
    baseStats: S({ health: 480, attack: 40, defense: 30, speed: 3, initiative: 50 }),
    baseAttack: 'strike',
    skillPresets: [skill('boss_earthshatter', 6), skill('boss_dark_blessing', 5)],
    passivePresets: [{ templateId: 'epass_thick_hide', level: 6 }, { templateId: 'epass_ward', level: 5 }],
    skillPriorities: ['boss_dark_blessing', 'boss_earthshatter'],
    threatTags: ['boss', 'tank'],
    spawnWeight: 1,
    isBoss: true,
    bossMechanics: ['reflect', 'damage_cap'],
    iconEmoji: '🛡️',
  },
  {
    id: 'boss_warlock_voidcaller',
    label: 'Зовущий Бездну Ксараг',
    raceId: 'demon',
    counterClass: 'warlock',
    baseStats: S({ health: 370, magicPower: 54, defense: 16, speed: 4, initiative: 62, critChance: 20 }),
    baseAttack: 'magic_bolt',
    skillPresets: [skill('boss_soul_drain', 6), skill('boss_unholy_nova', 6)],
    passivePresets: [{ templateId: 'epass_unstable_core', level: 6 }],
    skillPriorities: ['boss_soul_drain', 'boss_unholy_nova'],
    threatTags: ['boss', 'caster'],
    spawnWeight: 1,
    isBoss: true,
    bossMechanics: ['lifesteal', 'summon_minions'],
    iconEmoji: '👺',
  },
  {
    id: 'boss_berserker_bloodtide',
    label: 'Кровавый Прилив Грукк',
    raceId: 'orc',
    counterClass: 'berserker',
    baseStats: S({ health: 440, attack: 58, defense: 14, speed: 5, initiative: 58, critChance: 18 }),
    baseAttack: 'strike',
    skillPresets: [skill('boss_life_reap', 6), skill('boss_earthshatter', 6)],
    passivePresets: [{ templateId: 'epass_frenzied', level: 6 }, { templateId: 'epass_regrowth', level: 4 }],
    skillPriorities: ['boss_life_reap', 'boss_earthshatter'],
    threatTags: ['boss', 'bruiser'],
    spawnWeight: 1,
    isBoss: true,
    bossMechanics: ['enrage_below_half', 'lifesteal'],
    iconEmoji: '🪓',
  },
]

export const ENEMY_ARCHETYPES: EnemyArchetype[] = [
  ...COUNTER_ARCHETYPES,
  ...CHAOTIC_ARCHETYPES,
  ...HERO_NPC_ARCHETYPES,
  ...BOSSES,
]
