/**
 * 7 цепочек экспедиций (§12.4): 2 static + 5 procedural.
 */

import type { ExpeditionModeDef } from '../types/content'

export const EXPEDITIONS: ExpeditionModeDef[] = [
  {
    id: 'campaign-main',
    label: 'Основная кампания',
    kind: 'static',
    battleCountRange: [3, 3],
    partyMin: 1,
    partyMax: 4,
    interBattleReviveAllDowned: true,
    scenarioChain: ['tutorial', 'two-front', 'boss-lite'],
    description: 'Линейная кампания из трёх боёв. Между боями павшие союзники воскрешаются.',
  },
  {
    id: 'test-single-battle',
    label: 'Тестовый бой',
    kind: 'static',
    battleCountRange: [1, 1],
    partyMin: 1,
    partyMax: 4,
    interBattleReviveAllDowned: false,
    scenarioChain: ['tutorial'],
    description: 'Один отладочный бой для проверки сборки отряда.',
  },
  {
    id: 'chaotic-map',
    label: 'Хаотичная карта',
    kind: 'procedural',
    battleCountRange: [1, 3],
    partyMin: 1,
    partyMax: 4,
    interBattleReviveAllDowned: false,
    generatorId: 'chaotic-map',
    description: 'Случайное поле и от 1 до 20 врагов. Цепочка из 1–3 боёв.',
  },
  {
    id: 'tunnel',
    label: 'Тоннель',
    kind: 'procedural',
    battleCountRange: [2, 2],
    partyMin: 1,
    partyMax: 3,
    interBattleReviveAllDowned: false,
    generatorId: 'tunnel',
    description: 'Узкий коридор. Во втором бою ждёт враждебный герой или босс.',
  },
  {
    id: 'big-arena',
    label: 'Большая арена',
    kind: 'procedural',
    battleCountRange: [1, 1],
    partyMin: 2,
    partyMax: 4,
    interBattleReviveAllDowned: false,
    generatorId: 'big-arena',
    description: 'Просторная арена 10×20: 8–12 врагов и 1–3 босса в одном бою.',
  },
  {
    id: 'small-skirmish',
    label: 'Малая стычка',
    kind: 'procedural',
    battleCountRange: [1, 1],
    partyMin: 1,
    partyMax: 2,
    interBattleReviveAllDowned: false,
    generatorId: 'small-skirmish',
    description: 'Тесное поле 1×2: дуэль один на один.',
  },
  {
    id: 'ambush',
    label: 'Засада',
    kind: 'procedural',
    battleCountRange: [1, 1],
    partyMin: 2,
    partyMax: 4,
    interBattleReviveAllDowned: false,
    generatorId: 'ambush',
    description: 'Поле 10×10: отряд в центре против врагов по периметру.',
  },
]
