/**
 * Два пула модов Memento Mori (§16.13, §16.14).
 *
 * CARD_ITEM_MODS — каталог 29 (23 активных + 6 phase-2 enabled:false) для
 *   носителей карт и предметов. requires/excludes из CarrierTag.
 * PASSIVE_MODS — ровно 12, requires:['passive'].
 */

import type { ModTemplate } from '../types/memento'

export const CARD_ITEM_MODS: ModTemplate[] = [
  // --- damage ---
  {
    id: 'm_sharpen',
    label: 'Заточка',
    group: 'damage',
    requires: ['weapon'],
    descriptionLines: ['Увеличивает урон носителя.'],
    ops: [{ kind: 'damage_mult', base: 12, scaleMode: 'percent' }],
  },
  {
    id: 'm_brutal',
    label: 'Зверская сила',
    group: 'damage',
    requires: ['melee'],
    excludes: ['ranged'],
    descriptionLines: ['Ближние удары наносят больше урона.'],
    ops: [{ kind: 'damage_mult', base: 18, scaleMode: 'percent' }],
  },
  {
    id: 'm_arcane_power',
    label: 'Чародейская мощь',
    group: 'damage',
    requires: ['skill'],
    descriptionLines: ['Усиливает урон умений.'],
    ops: [{ kind: 'damage_mult', base: 15, scaleMode: 'percent' }],
  },
  {
    id: 'm_epicenter',
    label: 'Эпицентр',
    group: 'damage',
    requires: ['aoe'],
    descriptionLines: ['Цель в центре зоны получает усиленный урон.'],
    ops: [{ kind: 'aoe_center_damage_mult', base: 30, scaleMode: 'percent' }],
  },
  {
    id: 'm_precise',
    label: 'Точность',
    group: 'damage',
    requires: ['weapon'],
    descriptionLines: ['Повышает шанс критического удара.'],
    ops: [{ kind: 'crit_chance_add', base: 8, scaleMode: 'percent' }],
  },
  {
    id: 'm_deadeye',
    label: 'Меткий глаз',
    group: 'damage',
    requires: ['ranged'],
    excludes: ['melee'],
    descriptionLines: ['Дальние атаки чаще наносят крит.'],
    ops: [{ kind: 'crit_chance_add', base: 10, scaleMode: 'percent' }],
  },
  {
    id: 'm_lucky_strike',
    label: 'Счастливый удар',
    group: 'damage',
    requires: ['accessory'],
    descriptionLines: ['Аксессуар добавляет шанс крита владельцу.'],
    ops: [{ kind: 'crit_chance_add', base: 6, scaleMode: 'percent' }],
  },
  {
    id: 'm_flurry',
    label: 'Шквал',
    group: 'damage',
    requires: ['weapon'],
    descriptionLines: ['Иногда срабатывает дополнительный удар.'],
    ops: [{ kind: 'proc_extra_hit', baseChance: 25, hits: 1 }],
  },
  {
    id: 'm_double_tap',
    label: 'Двойной выстрел',
    group: 'damage',
    requires: ['ranged'],
    descriptionLines: ['Иногда выпускается ещё один снаряд.'],
    ops: [{ kind: 'proc_extra_hit', baseChance: 30, hits: 1 }],
  },
  // --- utility ---
  {
    id: 'm_long_arm',
    label: 'Дальнобойность',
    group: 'utility',
    requires: ['ranged'],
    descriptionLines: ['Увеличивает дальность дальних атак.'],
    ops: [{ kind: 'range_add', base: 1, scaleMode: 'flat' }],
  },
  {
    id: 'm_extend_reach',
    label: 'Длинная рукоять',
    group: 'utility',
    requires: ['weapon'],
    descriptionLines: ['Удлиняет досягаемость оружия.'],
    ops: [{ kind: 'range_add', base: 1, scaleMode: 'flat' }],
  },
  {
    id: 'm_wide_blast',
    label: 'Широкий взрыв',
    group: 'utility',
    requires: ['aoe'],
    descriptionLines: ['Увеличивает радиус зоны поражения.'],
    ops: [{ kind: 'aoe_size_add', base: 1, scaleMode: 'flat' }],
  },
  {
    id: 'm_quick_cast',
    label: 'Скорое сотворение',
    group: 'utility',
    requires: ['skill'],
    descriptionLines: ['Сокращает перезарядку умения.'],
    ops: [{ kind: 'cooldown_add', base: -1, scaleMode: 'flat' }],
  },
  {
    id: 'm_swift_step',
    label: 'Резвый шаг',
    group: 'utility',
    requires: ['accessory'],
    descriptionLines: ['Повышает инициативу владельца.'],
    ops: [{ kind: 'initiative_add', base: 10, scaleMode: 'flat' }],
  },
  // --- survival ---
  {
    id: 'm_vampiric',
    label: 'Вампиризм',
    group: 'survival',
    requires: ['melee'],
    descriptionLines: ['Часть нанесённого урона возвращается здоровьем.'],
    ops: [{ kind: 'lifesteal_pct', base: 15, scaleMode: 'percent' }],
  },
  {
    id: 'm_fortified',
    label: 'Укрепление',
    group: 'survival',
    requires: ['armor'],
    descriptionLines: ['Увеличивает максимальный запас здоровья.'],
    ops: [{ kind: 'carrier_hp_add', base: 30, scaleMode: 'flat' }],
  },
  {
    id: 'm_mending',
    label: 'Усиленное лечение',
    group: 'survival',
    requires: ['heal'],
    descriptionLines: ['Умения лечения восстанавливают больше здоровья.'],
    ops: [{ kind: 'heal_mult', base: 20, scaleMode: 'percent' }],
  },
  {
    id: 'm_healing_wave',
    label: 'Волна исцеления',
    group: 'survival',
    requires: ['heal'],
    descriptionLines: ['Часть лечения расплёскивается на соседей.'],
    ops: [{ kind: 'heal_splash', splashRatio: 35, scaleMode: 'percent' }],
  },
  {
    id: 'm_life_link',
    label: 'Связь жизни',
    group: 'survival',
    requires: ['skill'],
    descriptionLines: ['Применяя умение, владелец исцеляет себя.'],
    ops: [{ kind: 'self_heal_on_use', base: 10, scaleMode: 'percent' }],
  },
  {
    id: 'm_resilience',
    label: 'Стойкость',
    group: 'survival',
    requires: ['armor'],
    descriptionLines: ['Получив урон, владелец восстанавливает часть здоровья.'],
    ops: [{ kind: 'self_heal_on_damaged', base: 12, scaleMode: 'percent' }],
  },
  {
    id: 'm_vitality_charm',
    label: 'Амулет жизненной силы',
    group: 'survival',
    requires: ['accessory'],
    descriptionLines: ['Аксессуар прибавляет запас здоровья.'],
    ops: [{ kind: 'carrier_hp_add', base: 20, scaleMode: 'flat' }],
  },
  // --- defense ---
  {
    id: 'm_plated',
    label: 'Бронепластины',
    group: 'defense',
    requires: ['armor'],
    descriptionLines: ['Повышает защиту владельца.'],
    ops: [{ kind: 'defense_add', base: 8, scaleMode: 'flat' }],
  },
  {
    id: 'm_thorns',
    label: 'Шипы',
    group: 'defense',
    requires: ['armor'],
    descriptionLines: ['Атакующего врага ранит отражённый урон.'],
    ops: [{ kind: 'reflect_on_hit', base: 20, scaleMode: 'percent' }],
  },

  // --- phase-2 (enabled:false) ---
  {
    id: 'm_overcharge',
    label: 'Перегрузка зоны',
    group: 'damage',
    requires: ['aoe'],
    descriptionLines: ['Резко усиливает урон по площади.', 'Контент второй фазы.'],
    ops: [{ kind: 'damage_mult', base: 25, scaleMode: 'percent' }],
    enabled: false,
  },
  {
    id: 'm_guardian_ward',
    label: 'Оберег стража',
    group: 'defense',
    requires: ['accessory'],
    descriptionLines: ['Аксессуар прибавляет защиту.', 'Контент второй фазы.'],
    ops: [{ kind: 'defense_add', base: 6, scaleMode: 'flat' }],
    enabled: false,
  },
  {
    id: 'm_swift_strikes',
    label: 'Стремительные удары',
    group: 'damage',
    requires: ['melee'],
    descriptionLines: ['Иногда наносится добавочный ближний удар.', 'Контент второй фазы.'],
    ops: [{ kind: 'proc_extra_hit', baseChance: 20, hits: 1 }],
    enabled: false,
  },
  {
    id: 'm_blood_ritual',
    label: 'Кровавый ритуал',
    group: 'survival',
    requires: ['skill'],
    descriptionLines: ['Умения возвращают здоровье за счёт урона.', 'Контент второй фазы.'],
    ops: [{ kind: 'lifesteal_pct', base: 12, scaleMode: 'percent' }],
    enabled: false,
  },
  {
    id: 'm_haste_rune',
    label: 'Руна спешки',
    group: 'utility',
    requires: ['weapon'],
    descriptionLines: ['Оружие повышает инициативу.', 'Контент второй фазы.'],
    ops: [{ kind: 'initiative_add', base: 8, scaleMode: 'flat' }],
    enabled: false,
  },
  {
    id: 'm_grand_heal',
    label: 'Великое лечение',
    group: 'survival',
    requires: ['heal', 'skill'],
    descriptionLines: ['Сильно усиливает исцеляющие умения.', 'Контент второй фазы.'],
    ops: [{ kind: 'heal_mult', base: 30, scaleMode: 'percent' }],
    enabled: false,
  },
]

export const PASSIVE_MODS: ModTemplate[] = [
  {
    id: 'pm_empower',
    label: 'Усиление',
    group: 'damage',
    requires: ['passive'],
    descriptionLines: ['Усиливает урон от пассива.'],
    ops: [{ kind: 'damage_mult', base: 14, scaleMode: 'percent' }],
  },
  {
    id: 'pm_amplify',
    label: 'Резонанс',
    group: 'damage',
    requires: ['passive'],
    descriptionLines: ['Эффекты пассива бьют сильнее.'],
    ops: [{ kind: 'damage_mult', base: 20, scaleMode: 'percent' }],
  },
  {
    id: 'pm_focus',
    label: 'Сосредоточение',
    group: 'damage',
    requires: ['passive'],
    descriptionLines: ['Пассив добавляет шанс критического срабатывания.'],
    ops: [{ kind: 'crit_chance_add', base: 7, scaleMode: 'percent' }],
  },
  {
    id: 'pm_mend',
    label: 'Целебная искра',
    group: 'survival',
    requires: ['passive'],
    descriptionLines: ['Исцеление от пассива усиливается.'],
    ops: [{ kind: 'heal_mult', base: 18, scaleMode: 'percent' }],
  },
  {
    id: 'pm_toughen',
    label: 'Закалка',
    group: 'survival',
    requires: ['passive'],
    descriptionLines: ['Пассив прибавляет запас здоровья.'],
    ops: [{ kind: 'carrier_hp_add', base: 25, scaleMode: 'flat' }],
  },
  {
    id: 'pm_siphon',
    label: 'Подпитка',
    group: 'survival',
    requires: ['passive'],
    descriptionLines: ['Срабатывание пассива немного лечит владельца.'],
    ops: [{ kind: 'self_heal_on_use', base: 9, scaleMode: 'percent' }],
  },
  {
    id: 'pm_endure',
    label: 'Выносливость',
    group: 'survival',
    requires: ['passive'],
    descriptionLines: ['Получив урон, владелец залечивает раны.'],
    ops: [{ kind: 'self_heal_on_damaged', base: 10, scaleMode: 'percent' }],
  },
  {
    id: 'pm_overflow',
    label: 'Переполнение',
    group: 'survival',
    requires: ['passive'],
    descriptionLines: ['Пассив крадёт часть нанесённого урона как здоровье.'],
    ops: [{ kind: 'lifesteal_pct', base: 11, scaleMode: 'percent' }],
  },
  {
    id: 'pm_potency',
    label: 'Изобилие',
    group: 'survival',
    requires: ['passive'],
    descriptionLines: ['Лечение пассива частично расплёскивается на союзников.'],
    ops: [{ kind: 'heal_splash', splashRatio: 25, scaleMode: 'percent' }],
  },
  {
    id: 'pm_bulwark',
    label: 'Оплот',
    group: 'defense',
    requires: ['passive'],
    descriptionLines: ['Пассив повышает защиту владельца.'],
    ops: [{ kind: 'defense_add', base: 7, scaleMode: 'flat' }],
  },
  {
    id: 'pm_reflect',
    label: 'Отражение',
    group: 'defense',
    requires: ['passive'],
    descriptionLines: ['Часть полученного урона возвращается атакующему.'],
    ops: [{ kind: 'reflect_on_hit', base: 15, scaleMode: 'percent' }],
  },
  {
    id: 'pm_haste',
    label: 'Проворство',
    group: 'utility',
    requires: ['passive'],
    descriptionLines: ['Пассив повышает инициативу владельца.'],
    ops: [{ kind: 'initiative_add', base: 9, scaleMode: 'flat' }],
  },
]
