/**
 * Пассивные навыки (§7, §17). 32 пассива героев (8 классов × 4) +
 * 10 пассивов врагов (isEnemy:true). Все tags включают 'passive'.
 */

import type { PassiveTemplate } from '../types/content'

export const HERO_PASSIVES: PassiveTemplate[] = [
  // --- warrior ---
  {
    id: 'pass_warrior_resolve',
    label: 'Несгибаемость',
    trigger: 'on_battle_start',
    procChance: 1,
    description: 'В начале боя повышает защиту воина.',
    effect: { type: 'stat', mods: { defense: 8, health: 20 } },
    tags: ['passive', 'warrior', 'survival'],
  },
  {
    id: 'pass_warrior_momentum',
    label: 'Натиск',
    trigger: 'on_strike',
    procChance: 0.4,
    description: 'Удар иногда наносит добавочный физический урон.',
    effect: { type: 'damage_on_trigger', token: '30%%' },
    tags: ['passive', 'warrior', 'damage'],
  },
  {
    id: 'pass_warrior_second_wind',
    label: 'Второе дыхание',
    trigger: 'on_damaged',
    procChance: 0.3,
    description: 'Получив урон, воин восстанавливает часть здоровья.',
    effect: { type: 'heal_on_trigger', token: '20%%' },
    tags: ['passive', 'warrior', 'survival'],
  },
  {
    id: 'pass_warrior_bulwark',
    label: 'Оплот',
    trigger: 'on_turn_start',
    procChance: 1,
    description: 'Каждый ход воин держит защитную стойку.',
    effect: { type: 'shield_on_trigger', token: '15%%50' },
    tags: ['passive', 'warrior', 'defense'],
  },
  // --- mage ---
  {
    id: 'pass_mage_arcane_mind',
    label: 'Магический разум',
    trigger: 'on_battle_start',
    procChance: 1,
    description: 'Усиливает силу магии и ману на весь бой.',
    effect: { type: 'stat', mods: { magicPower: 12, mana: 15 } },
    tags: ['passive', 'mage', 'utility'],
  },
  {
    id: 'pass_mage_overload',
    label: 'Перегрузка',
    trigger: 'on_card_use',
    procChance: 0.35,
    description: 'Применённое умение иногда взрывается дополнительной волной.',
    effect: { type: 'damage_on_trigger', token: '35%%' },
    tags: ['passive', 'mage', 'damage'],
  },
  {
    id: 'pass_mage_mana_shield',
    label: 'Мановый щит',
    trigger: 'on_damaged',
    procChance: 0.4,
    description: 'Часть входящего урона поглощается магией.',
    effect: { type: 'shield_on_trigger', token: '25%%' },
    tags: ['passive', 'mage', 'defense'],
  },
  {
    id: 'pass_mage_arcane_surge',
    label: 'Чародейский всплеск',
    trigger: 'on_kill',
    procChance: 0.5,
    description: 'Убийство врага восстанавливает магу здоровье.',
    effect: { type: 'heal_on_trigger', token: '20%%' },
    tags: ['passive', 'mage', 'utility'],
  },
  // --- ranger ---
  {
    id: 'pass_ranger_keen_eye',
    label: 'Острый глаз',
    trigger: 'on_battle_start',
    procChance: 1,
    description: 'Повышает шанс крита и скорость следопыта.',
    effect: { type: 'stat', mods: { critChance: 10, speed: 1 } },
    tags: ['passive', 'ranger', 'utility'],
  },
  {
    id: 'pass_ranger_volley',
    label: 'Залп',
    trigger: 'on_strike',
    procChance: 0.45,
    description: 'Выстрел иногда поражает цель дважды.',
    effect: { type: 'damage_on_trigger', token: '25%%' },
    tags: ['passive', 'ranger', 'damage'],
  },
  {
    id: 'pass_ranger_evasion',
    label: 'Уклонение',
    trigger: 'on_damaged',
    procChance: 0.3,
    description: 'Следопыт ловко смягчает удары.',
    effect: { type: 'shield_on_trigger', token: '20%%' },
    tags: ['passive', 'ranger', 'survival'],
  },
  {
    id: 'pass_ranger_hunters_mark',
    label: 'Метка охотника',
    trigger: 'on_kill',
    procChance: 0.6,
    description: 'После добивания цели следопыт восстанавливает дыхание.',
    effect: { type: 'heal_on_trigger', token: '18%%' },
    tags: ['passive', 'ranger', 'utility'],
  },
  // --- healer ---
  {
    id: 'pass_healer_grace',
    label: 'Благодать',
    trigger: 'on_battle_start',
    procChance: 1,
    description: 'Усиливает силу исцеления целителя.',
    effect: { type: 'stat', mods: { healPower: 14, defense: 4 } },
    tags: ['passive', 'healer', 'utility'],
  },
  {
    id: 'pass_healer_overflow',
    label: 'Перелив',
    trigger: 'on_heal',
    procChance: 0.5,
    description: 'Лечение иногда переливается на самого целителя.',
    effect: { type: 'heal_on_trigger', token: '30%%' },
    tags: ['passive', 'healer', 'survival'],
  },
  {
    id: 'pass_healer_aegis',
    label: 'Эгида веры',
    trigger: 'on_turn_start',
    procChance: 1,
    description: 'Каждый ход вокруг целителя мерцает щит.',
    effect: { type: 'shield_on_trigger', token: '12%%40' },
    tags: ['passive', 'healer', 'defense'],
  },
  {
    id: 'pass_healer_retribution',
    label: 'Возмездие',
    trigger: 'on_damaged',
    procChance: 0.35,
    description: 'Атакующего целителя обжигает святой свет.',
    effect: { type: 'damage_on_trigger', token: '22%%' },
    tags: ['passive', 'healer', 'damage'],
  },
  // --- rogue ---
  {
    id: 'pass_rogue_ambush',
    label: 'Засада',
    trigger: 'on_battle_start',
    procChance: 1,
    description: 'В начале боя разбойник особенно смертоносен.',
    effect: { type: 'stat', mods: { critChance: 15, attack: 6 } },
    tags: ['passive', 'rogue', 'damage'],
  },
  {
    id: 'pass_rogue_backstab',
    label: 'Удар в спину',
    trigger: 'on_strike',
    procChance: 0.4,
    description: 'Атака иногда наносит коварный добавочный урон.',
    effect: { type: 'damage_on_trigger', token: '40%%' },
    tags: ['passive', 'rogue', 'damage'],
  },
  {
    id: 'pass_rogue_shadowstep',
    label: 'Тенеход',
    trigger: 'on_damaged',
    procChance: 0.35,
    description: 'Получив урон, разбойник растворяется в тенях.',
    effect: { type: 'shield_on_trigger', token: '25%%' },
    tags: ['passive', 'rogue', 'survival'],
  },
  {
    id: 'pass_rogue_bloodlust',
    label: 'Жажда крови',
    trigger: 'on_kill',
    procChance: 0.55,
    description: 'Убийство возвращает разбойнику здоровье.',
    effect: { type: 'heal_on_trigger', token: '22%%' },
    tags: ['passive', 'rogue', 'survival'],
  },
  // --- paladin ---
  {
    id: 'pass_paladin_devotion',
    label: 'Преданность',
    trigger: 'on_battle_start',
    procChance: 1,
    description: 'Паладин начинает бой под защитой света.',
    effect: { type: 'stat', mods: { defense: 12, healPower: 8, health: 25 } },
    tags: ['passive', 'paladin', 'defense'],
  },
  {
    id: 'pass_paladin_lay_hands',
    label: 'Наложение рук',
    trigger: 'on_turn_start',
    procChance: 0.5,
    description: 'Каждый ход паладин может исцелить себя.',
    effect: { type: 'heal_on_trigger', token: '18%%' },
    tags: ['passive', 'paladin', 'survival'],
  },
  {
    id: 'pass_paladin_consecration',
    label: 'Освящение',
    trigger: 'on_damaged',
    procChance: 0.4,
    description: 'Враг, ударивший паладина, опаляется святостью.',
    effect: { type: 'damage_on_trigger', token: '25%%' },
    tags: ['passive', 'paladin', 'damage'],
  },
  {
    id: 'pass_paladin_guardian',
    label: 'Страж',
    trigger: 'on_turn_start',
    procChance: 1,
    description: 'Паладин постоянно держит священный барьер.',
    effect: { type: 'shield_on_trigger', token: '14%%50' },
    tags: ['passive', 'paladin', 'defense'],
  },
  // --- warlock ---
  {
    id: 'pass_warlock_dark_pact',
    label: 'Тёмный пакт',
    trigger: 'on_battle_start',
    procChance: 1,
    description: 'Чернокнижник жертвует прочностью ради мощи.',
    effect: { type: 'stat', mods: { magicPower: 18, critChance: 8 } },
    tags: ['passive', 'warlock', 'damage'],
  },
  {
    id: 'pass_warlock_siphon',
    label: 'Иссушение',
    trigger: 'on_card_use',
    procChance: 0.4,
    description: 'Применённое заклинание иногда крадёт жизнь.',
    effect: { type: 'heal_on_trigger', token: '25%%' },
    tags: ['passive', 'warlock', 'survival'],
  },
  {
    id: 'pass_warlock_curse_weave',
    label: 'Сплетение порчи',
    trigger: 'on_strike',
    procChance: 0.35,
    description: 'Атака чернокнижника иногда выплёскивает порчу.',
    effect: { type: 'damage_on_trigger', token: '38%%' },
    tags: ['passive', 'warlock', 'damage'],
  },
  {
    id: 'pass_warlock_soul_armor',
    label: 'Доспех душ',
    trigger: 'on_kill',
    procChance: 0.6,
    description: 'Поглощённая душа павшего окутывает щитом.',
    effect: { type: 'shield_on_trigger', token: '30%%' },
    tags: ['passive', 'warlock', 'defense'],
  },
  // --- berserker ---
  {
    id: 'pass_berserker_rage',
    label: 'Ярость',
    trigger: 'on_battle_start',
    procChance: 1,
    description: 'Берсерк входит в бой в неистовстве.',
    effect: { type: 'stat', mods: { attack: 16, speed: 1 } },
    tags: ['passive', 'berserker', 'damage'],
  },
  {
    id: 'pass_berserker_frenzy',
    label: 'Неистовство',
    trigger: 'on_strike',
    procChance: 0.5,
    description: 'Удары берсерка иногда сыплются градом.',
    effect: { type: 'damage_on_trigger', token: '45%%' },
    tags: ['passive', 'berserker', 'damage'],
  },
  {
    id: 'pass_berserker_bloodbath',
    label: 'Кровавая баня',
    trigger: 'on_kill',
    procChance: 0.6,
    description: 'Каждое убийство распаляет берсерка и лечит его.',
    effect: { type: 'heal_on_trigger', token: '28%%' },
    tags: ['passive', 'berserker', 'survival'],
  },
  {
    id: 'pass_berserker_pain_fuel',
    label: 'Топливо боли',
    trigger: 'on_damaged',
    procChance: 0.45,
    description: 'Боль лишь подстёгивает контратаку берсерка.',
    effect: { type: 'damage_on_trigger', token: '30%%' },
    tags: ['passive', 'berserker', 'damage'],
  },
]

export const ENEMY_PASSIVES: PassiveTemplate[] = [
  {
    id: 'epass_thick_hide',
    label: 'Толстая шкура',
    trigger: 'on_battle_start',
    procChance: 1,
    description: 'Существо обладает природной бронёй.',
    effect: { type: 'stat', mods: { defense: 10, health: 30 } },
    tags: ['passive', 'enemy', 'defense'],
    isEnemy: true,
  },
  {
    id: 'epass_savage',
    label: 'Свирепость',
    trigger: 'on_strike',
    procChance: 0.4,
    description: 'Атака врага иногда наносит добавочный урон.',
    effect: { type: 'damage_on_trigger', token: '30%%' },
    tags: ['passive', 'enemy', 'damage'],
    isEnemy: true,
  },
  {
    id: 'epass_regrowth',
    label: 'Регенерация плоти',
    trigger: 'on_turn_start',
    procChance: 0.5,
    description: 'Существо медленно залечивает раны.',
    effect: { type: 'heal_on_trigger', token: '15%%' },
    tags: ['passive', 'enemy', 'survival'],
    isEnemy: true,
  },
  {
    id: 'epass_spiky',
    label: 'Шипы',
    trigger: 'on_damaged',
    procChance: 0.6,
    description: 'Атакующего врага ранят шипы.',
    effect: { type: 'damage_on_trigger', token: '20%%' },
    tags: ['passive', 'enemy', 'damage'],
    isEnemy: true,
  },
  {
    id: 'epass_frenzied',
    label: 'Бешенство',
    trigger: 'on_kill',
    procChance: 0.7,
    description: 'После добивания существо впадает в раж.',
    effect: { type: 'stat', mods: { attack: 12, speed: 1 } },
    tags: ['passive', 'enemy', 'damage'],
    isEnemy: true,
  },
  {
    id: 'epass_ward',
    label: 'Защитный оберег',
    trigger: 'on_turn_start',
    procChance: 1,
    description: 'Существо окружено мерцающим оберегом.',
    effect: { type: 'shield_on_trigger', token: '12%%40' },
    tags: ['passive', 'enemy', 'defense'],
    isEnemy: true,
  },
  {
    id: 'epass_undying',
    label: 'Неупокоенность',
    trigger: 'on_damaged',
    procChance: 0.3,
    description: 'Нежить цепляется за подобие жизни.',
    effect: { type: 'heal_on_trigger', token: '18%%' },
    tags: ['passive', 'enemy', 'survival'],
    isEnemy: true,
  },
  {
    id: 'epass_venomous',
    label: 'Ядовитость',
    trigger: 'on_strike',
    procChance: 0.45,
    description: 'Атаки существа сочатся ядом.',
    effect: { type: 'damage_on_trigger', token: '25%%' },
    tags: ['passive', 'enemy', 'damage'],
    isEnemy: true,
  },
  {
    id: 'epass_warcaller',
    label: 'Призыв к битве',
    trigger: 'on_battle_start',
    procChance: 1,
    description: 'Вожак воодушевляет себя перед сечей.',
    effect: { type: 'stat', mods: { attack: 10, critChance: 6 } },
    tags: ['passive', 'enemy', 'utility'],
    isEnemy: true,
  },
  {
    id: 'epass_unstable_core',
    label: 'Нестабильное ядро',
    trigger: 'on_damaged',
    procChance: 0.4,
    description: 'Поврежденный голем выбрасывает энергию.',
    effect: { type: 'damage_on_trigger', token: '28%%' },
    tags: ['passive', 'enemy', 'damage'],
    isEnemy: true,
  },
]

export const ALL_PASSIVES: PassiveTemplate[] = [...HERO_PASSIVES, ...ENEMY_PASSIVES]
